[tool.poetry.dependencies]
black = "24.4.2"
eth-utils = "4.1.1"
poly_eip712_structs = "0.0.1"
pytest = "8.2.2"
python-dotenv = "0.19.2"
requests = "2.32.3"
websockets = "12.0"
py_order_utils = { git = "https://github.com/felixjchen/python-order-utils.git", rev = "21613870c2f67930fff4ac942dc1aa1ed538830e" }
